---
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,controversial,design,naming,unusedcode"
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- test/
- coverage/
- doc/
- vendor/
- bench/
- .*
